# sklearn.preprocessing - 데이터 전처리
* Null, NaN 값 대체
* 문자열 값을 인코딩 하여 숫자 형으로 변환

## 데이터 인코딩

### 레이블 인코딩 ( LabelEncoder )
* 카테고리 피처를 코드형 숫자 값으로 변환

In [11]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)                 # 인코딩 변환값
print(encoder.classes_)       # 인코딩 클래스 (순서대로 인덱스 0 ~ 5)
print(encoder.inverse_transform(labels))

[0 1 4 5 3 3 2 2]
['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


* 숫자 값의 경우 크고 작음에 대한 특성이 작용하여 예측 성능이 떨어지는 경우 발생
* 레이블 인코딩은 선형 회귀와 같은 ML 알고리즘에는 적용하지 않는다.
* 트리 계열의 ML 알고리즘은 숫자의 이러한 특성을 반영하지 않으므로 적용 가능하다.

### 원-핫 인코딩 ( OneHotEncoder)
* 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시하는 방식.

#### 주의할 점
1. OneHotEncoder로 변환하기 전에 모든 문자열 값이 숫자형 값으로 변환돼야 한다.
2. 입력 값으로 2차원 데이터가 필요하다.

In [19]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 문자열 값을 숫자형 값으로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환
labels = labels.reshape(-1,1)
onehot = OneHotEncoder()
onehot.fit(labels)
oh_labels = onehot.transform(labels)
print(oh_labels.toarray()) # toarray : 리스트 등의 자료형을 배열로 변환
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


### pandas의 get_dummies()
* OneHotEncoder와 다르게 문자열 카테고리 값을 숫자 형으로 변환할 필요 없이 바로 변환 가능

In [21]:
import pandas as pd
df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### 피처 스케일링과 정규화
스케일링 : 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업
* 표준화 : 데이터의 피처 각각이 평균이 0이고 분산이 1인 가우시안 정규 분포를 가진 값으로 변환

> $x_inew = (x_i-mean(x)) / stdev(x)$

* 정규화 : 서로 다른 피처의 크기가 동일하기 위해 크기를 변환

> $x_inew = (x_i-min(x)) / (max(x) - min(x))$

### StandardScaler
* RBF 커널을 이용하는 서포트 벡터 머신, 선형 회귀, 로지스틱 회귀는 데이터가 가우시안 분포를 가지고 있다고 가정

In [30]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
X = iris.data
y = iris.target
data = pd.DataFrame(data = X, columns=iris.feature_names)
data

from sklearn.preprocessing import StandardScaler

std = StandardScaler()
std.fit(X)
X_std = std.transform(X)

pd.DataFrame(X_std, columns=iris.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

### MinMaxScaler
* 데이터 값을 0과 1 사이의 범위 값으로 변환(음수 값이 있으면 -1, 1값으로 변환)
* 데이터의 분포가 가우시안 분포가 아닐 경우 Min, Max Scale 적용

In [32]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X)
X_scaler = scaler.transform(X)

pd.DataFrame(X_scaler, columns=iris.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

### fit(), transform()
* fit() : 데이터 변환을 위한 기준 정보 설정 적용
* transform() : fit에서 설정된 정보를 이용해 데이터 변환
* fit_transform() : fit(), transform() 한 번에 적용

#### 주의할 점
1. 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리
2. 1이 여의치 않다면 테스트 데이터 변환시에는 fit(), fit_transform()을 적용하지 않고 학습데이터로 이미 fit()된 Scaler객체를 이용해 transform()으로 변환