# 넘파이 ndarray

In [8]:
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3],[2,3,4]])
array3 = np.array([[1,2,3]])

print(array1.ndim,'차원' ,array1.shape)
print(array2.ndim,'차원' ,array2.shape)
print(array3.ndim,'차원' ,array3.shape)

1 차원 (3,)
2 차원 (2, 3)
2 차원 (1, 3)


* ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능.
* ex) int와 float가 함께 있을 수 없다.
* astype() : 데이터 타입을 바꾸는 함수

## axis 축
* <1차원> 
##### axis 0

* <2차원> 
##### axis 0 : 행
##### axis1 : 열

* axis기반의 연산함수 수행

In [13]:
print(array2)
print(array2.sum())                # 모든 원소의 값 계산
print(array2.sum(axis=0))          # 행의 방향으로 계산
print(array2.sum(axis=1))          # 열의 방향으로 계산

[[1 2 3]
 [2 3 4]]
15
[3 5 7]
[6 9]


## ndarray 생성
* arrange(), zeros(), ones()

In [18]:
print(np.arange(10))
print(np.zeros((3,2)))
print(np.ones((3,2)))

[0 1 2 3 4 5 6 7 8 9]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


* reshape()

In [31]:
list1 = np.arange(10)
print(list1)
print(list1.reshape(2,5))
print(list1.reshape(-1,5))      # 열이 5로 고정되고 행이 자동으로 맞춰짐
print(list1.reshape(-1,2))

array2d = list1.reshape(-1,2)
print(array1d.reshape(-1,))     # 5 x 2 형태의 2차원 데이터를 1차원으로 변경

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


## 인덱싱(indexing)

### 인덱싱 유형
##### 특정 위치의 단일값 추출

In [52]:
# 1차원 ndarray
array1d = np.arange(10)
print(array1d)
print(array1d[1])

# 2차원 ndarray
array2d = array1d.reshape(-1,5)
print(array2d)
print(array2d[0,0])
print(array2d[1,4])

[0 1 2 3 4 5 6 7 8 9]
1
[[0 1 2 3 4]
 [5 6 7 8 9]]
0
9


##### 슬라이싱
* 연속된 인덱스 상의 ndarray를 추출

In [46]:
# 슬라이싱
# 1차원 ndarray
print(array1d[3:5])

# 2차원 ndarray
print(array2d[0:2, 0:2])

[3 4]
[[0 1]
 [5 6]]


##### 팬시 인덱싱
* 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 추출

In [60]:
# 1차원 ndarray
print(array1d[[2,4,8]])

# 2차원 ndarray
print(array2d[[0,1],[2]])
print(array2d[[0,1],2:4])

[2 4 8]
[2 7]
[[2 3]
 [7 8]]


##### 불린 인덱싱
* 특정 조건에 해당하는지의 여부인 True / False값 인덱싱 집합을 기반으로 True에 해당하는 인덱스를 추출

In [68]:
# 불린 인덱싱
# 1차원 ndarray
print(array1d[array1d>5])

# 2차원 ndarray
print(array2d[array2d>2])

[6 7 8 9]
[3 4 5 6 7 8 9]


## 배열의 정렬 - sort(), argsort()

### sort()
* np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
* ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None
* 기본적으로 디폴트는 오름차순 정렬. 내림차순 정렬을 위해서는 [::-1]을 적용. ex) np.sort()[::-1]

##### 2차원 배열에서 axis를 기반으로 하는 sort()
* np.sort(A, axis=0) : 행 방향을 기준으로 각 열에 대한 오름차순 정렬
* np.sort(A, axis=1) : 열 방향을 기준으로 각 행에 대한 오름차순 정렬

In [72]:
array1 = np.array([[3,8,4],[7,1,6]])
print(array1) 
print(np.sort(array1, axis=0))
print(np.sort(array1, axis=1))

[[3 8 4]
 [7 1 6]]
[[3 1 4]
 [7 8 6]]
[[3 4 8]
 [1 6 7]]


### argsort()
* 원본 행렬 정렬 시 정렬된 행렬의 원래 인덱스를 필요로 하는 경우 사용.

In [77]:
array2 = np.array([3,1,9,5])
print(array2)
print(np.sort(array2))
print(np.argsort(array2))        # 원본 행렬 인덱스를 ndarray형태로 반환

[3 1 9 5]
[1 3 5 9]
[1 0 3 2]


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

### 행렬 내적(행렬 곱)
* np.dot()

In [84]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
            [9,10],
            [11,12]])
print(np.dot(A,B))

[[ 58  64]
 [139 154]]


### 전치 행렬
* np.transpose()

In [85]:
A = np.array([[1,2],[3,4]])
print(np.transpose(A))

[[1 3]
 [2 4]]
